### ISSUE TITLE
Mistake in Chapter 16

### ISSUE THREAD

**Issue by uzhas-sovka** [larrybotha/haskell-book#8]
(>>=) :: Monad f =>       f a -> f (a -> f b) f b

has to be
(>>=) :: Monad f =>       f a -> f (a -> f b)  -> f b

PS. Thanks a lot, great _additional layer of structure_ over Allen/Moronuki book.

**Comment by larrybotha** [comment]
Did you mean chapter 18?

I found the issue here: https://github.com/larrybotha/haskell-book/commit/cabde57e9a76439ebafd488d33a7a93467f358f0

Thanks; I'm a slow learner, so I've needed to really hash things out for myself O.o

Watch out for chapter 21... those Traversables got me (and ended me, for now...)!

**Comment by uzhas-sovka** [comment]
Yep. my error, 18.
